name: backup-sqlite

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Dump SQLite
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl ssh console -C "sqlite3 /data/ais.db '.backup ais-backup.db'" --select=instance
          flyctl ssh console -C "tar czf ais-backup.tar.gz ais-backup.db" --select=instance
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ais-sqlite-backup
          path: ais-backup.tar.gz
          retention-days: 14
